- name: test
  hosts: all
  tasks:
    - name: find all the files
      find:
        paths: /home/tomcatplay/test
        patterns: '*.sh'
      register: shell_files
    - debug:
        msg: "{{ item }}"
      loop: "{{shell_files.files}}"
#here we all the information about the shell files in sample4.yml we will try to get only path output